"""empty message

Revision ID: 012bad5f6c39
Revises: 9599a6cd42ab
Create Date: 2023-03-23 13:30:08.371602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012bad5f6c39'
down_revision = '9599a6cd42ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_description',
    sa.Column('domain_description', sa.String(length=180), nullable=True),
    sa.Column('domainid', sa.Integer(), nullable=True),
    sa.Column('domain_descid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domainid'], ['domain.domainid'], ),
    sa.PrimaryKeyConstraint('domain_descid')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activitydesc', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_column('activitydesc')

    op.drop_table('domain_description')
    # ### end Alembic commands ###
