"""Added unit, response, and student ID info

Revision ID: 1f16c0557f7d
Revises: 894999911626
Create Date: 2022-10-02 17:25:39.531443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f16c0557f7d'
down_revision = '894999911626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit',
    sa.Column('unitid', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('required_minutes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('unitid')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unitid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('responseid', sa.String(length=64), nullable=True))
        batch_op.create_foreign_key("fk_activity_log_unit_unitid", 'unit', ['unitid'], ['unitid'])

    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.drop_column('core')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_number', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_student_student_number'), ['student_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_student_number'))
        batch_op.drop_column('student_number')

    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.add_column(sa.Column('core', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_constraint("fk_activity_log_unit_unitid", type_='foreignkey')
        batch_op.drop_column('responseid')
        batch_op.drop_column('unitid')

    op.drop_table('unit')
    # ### end Alembic commands ###
