"""Added counts_prev column to unit

Revision ID: 59e7b548d08a
Revises: 1f16c0557f7d
Create Date: 2022-10-06 18:04:26.126103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59e7b548d08a'
down_revision = '1f16c0557f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('counts_prev', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit', schema=None) as batch_op:
        batch_op.drop_column('counts_prev')

    # ### end Alembic commands ###
