"""empty message

Revision ID: 894999911626
Revises: 8affcc5e59ab
Create Date: 2022-09-19 01:42:45.820998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894999911626'
down_revision = '8affcc5e59ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.add_column(sa.Column('core', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.drop_column('core')

    # ### end Alembic commands ###
