"""empty message

Revision ID: 8affcc5e59ab
Revises: 078c0c71ca83
Create Date: 2022-08-14 21:01:22.223557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8affcc5e59ab'
down_revision = '078c0c71ca83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('activityid', sa.Integer(), nullable=False),
    sa.Column('activity', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('activityid')
    )
    op.create_table('domain',
    sa.Column('domainid', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('domainid')
    )
    op.create_table('location',
    sa.Column('locationid', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('locationid')
    )
    op.create_table('student',
    sa.Column('studentid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('studentid')
    )
    op.create_table('supervisor',
    sa.Column('supervisorid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('supervisorid')
    )
    op.create_table('activity_log',
    sa.Column('logid', sa.Integer(), nullable=False),
    sa.Column('studentid', sa.Integer(), nullable=True),
    sa.Column('locationid', sa.Integer(), nullable=True),
    sa.Column('supervisorid', sa.Integer(), nullable=True),
    sa.Column('activityid', sa.Integer(), nullable=True),
    sa.Column('domainid', sa.Integer(), nullable=True),
    sa.Column('minutes_spent', sa.Integer(), nullable=True),
    sa.Column('record_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['activityid'], ['activity.activityid'], ),
    sa.ForeignKeyConstraint(['domainid'], ['domain.domainid'], ),
    sa.ForeignKeyConstraint(['locationid'], ['location.locationid'], ),
    sa.ForeignKeyConstraint(['studentid'], ['student.studentid'], ),
    sa.ForeignKeyConstraint(['supervisorid'], ['supervisor.supervisorid'], ),
    sa.PrimaryKeyConstraint('logid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_log')
    op.drop_table('supervisor')
    op.drop_table('student')
    op.drop_table('location')
    op.drop_table('domain')
    op.drop_table('activity')
    # ### end Alembic commands ###
