"""Add DB update table

Revision ID: 9599a6cd42ab
Revises: 59e7b548d08a
Create Date: 2022-10-17 14:10:33.398734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9599a6cd42ab'
down_revision = '59e7b548d08a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_db_update',
    sa.Column('updateid', sa.Integer(), nullable=False),
    sa.Column('updatedate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('updateid')
    )
    with op.batch_alter_table('last_db_update', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_last_db_update_updatedate'), ['updatedate'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('last_db_update', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_last_db_update_updatedate'))

    op.drop_table('last_db_update')
    # ### end Alembic commands ###
