"""empty message

Revision ID: f5f52b9b9f93
Revises: 56affa8e1d74
Create Date: 2023-05-03 12:55:04.194526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5f52b9b9f93'
down_revision = '56affa8e1d74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.alter_column('is_edited',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.alter_column('is_edited',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
